FROM python:3.8-slim

WORKDIR /app

COPY . .

# Install Flask
RUN pip install Flask

# Set environment variable
ENV FLASK_APP=app.py

EXPOSE 8080

# Run the Flask app
CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]