pipeline {
    agent any
    
    environment {
        // Define variables for Docker Hub credentials
        DOCKERHUB_CREDENTIALS = credentials('docker-hub-credentials')
        DOCKERHUB_USERNAME = DOCKERHUB_CREDENTIALS.username
        DOCKERHUB_PASSWORD = DOCKERHUB_CREDENTIALS.password
        IMAGE_NAME = "bharathikalai/your-image-name:latest"
    }
    
    stages {
        stage('Checkout') {
            steps {
                script {
                    // Checkout the code from Git repository
                    git credentialsId: 'git-credentials-id', url: 'https://github.com/your/repo.git'
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image
                    docker.build("${IMAGE_NAME}:${env.BUILD_NUMBER}")
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    // Authenticate and push Docker image to Docker Hub
                    docker.withRegistry('', DOCKERHUB_USERNAME, DOCKERHUB_PASSWORD) {
                        docker.image("${IMAGE_NAME}:${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }
    }
    
    post {
        always {
            // Clean up Docker images after build
            script {
                docker.image("${IMAGE_NAME}:${env.BUILD_NUMBER}").remove()
            }
        }
    }
}
