pipeline {
    agent any

    environment {
        // Define variables for referencing credentials
        DOCKERHUB_USR = credentials('dockerhub-username') // Your DockerHub username
        DOCKERHUB_PSW = credentials('dockerhub-password') // Your DockerHub password
        IMAGE_NAME = 'bharathikalai/jenkins:latest' // Replace with your image name or another credential if needed
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm // This will check out your repository into Jenkins workspace
                sh 'ls -la' 
                sh 'pwd'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image
                    docker.build("${IMAGE_NAME}", "/var/lib/jenkins/workspace/docker/build_application_docker")
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    // Log in to Docker Hub using the credentials
                    sh 'echo $DOCKERHUB_PSW | docker login -u $DOCKERHUB_USR --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // Push Docker image to Docker Hub
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_USR) {
                        docker.image("${IMAGE_NAME}").push()
                    }
                }
            }
        }
    }

    post {
        always {
            // Clean up Docker images after build
            script {
                docker.image("${IMAGE_NAME}").remove()
            }
        }
    }
}
